url: https://vkumar33.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: Vikas Kumar
email: vkumar33@uic.edu
description: "CS424"



# Build settings
markdown: kramdown
permalink: pretty
